### PR TITLE
TLC for homepage

### PR DESCRIPTION
**Pull request by JMStewart00**
- Max width on content
- Event/Meetings cleanup and massaging
- more maintainable urbancountycouncil block

## Summary / Approach

Just trying to do some housekeeping. Weird markup and weird CSS all over the place makes it a bit difficult.

## Testing Instruction(s)

Check out the homepage. I _**think**_ the changes only touched the homepage

## Screenshots

Lexington_ Kentucky_ Horse Capital of the World_ (1)

## Metadata

| Question | Answer |
|----------|--------|
| Did you perform a self-review of this PR? | yes
| Documentation reflects changes? | n/a
| Unit/Functional tests reflect changes? | n/a
| Did you perform browser testing? | yes, Chrome, FF
| Did you provide detail in the summary on how and where to test this branch? | yes
| Relevant links | https://apaxsoftware.atlassian.net/browse/LG-138

### CODE REVIEW

**Comment by TaylorAkin** [comment]
[Visit Site](https://pr-464-lexky-d8.pantheonsite.io/)

Created multidev environment [pr-464](https://dashboard.pantheon.io/sites/085efc9d-6f4f-4d02-a80b-9d5cf086a982#pr-464) for lexky-d8.

**Comment by JMStewart00** [comment]
@TaylorAkin I hate everything about this PR but there's a new screenshot and updates have been made

**Review by TaylorAkin — COMMENTED** [review]
Screenshot 2023-09-11 at 11 20 36 AM

Title is getting cutoff

**Comment by TaylorAkin** [comment]
Screenshot 2023-09-11 at 11 21 42 AM

Maybe we wrap earlier

**Comment by TaylorAkin** [comment]
Screenshot 2023-09-11 at 2 47 58 PM

Meeting cards on /departments/urban-county-council

**Review by TaylorAkin — APPROVED** [review]

**Pull request merged**
